services:
  database:
    container_name: ${CONTAINER_NAME}-database
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$DATABASE_ROOT_PASSWORD" ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    container_name: ${CONTAINER_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - internal

  wordpress:
    build:
      context: .
      dockerfile: docker/Dockerfile.wordpress
    restart: always
    container_name: ${CONTAINER_NAME}-wordpress
    ports:
      - 80:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
      WORDDPRESS_DEBUG: '${WORDPRESS_DEBUG}'
    depends_on:
      - database
    volumes:
      - ./src:/var/www/html/wp-content:rw
      - wp-content_uploads:/var/www/html/wp-content/uploads
    networks:
      - internal

  my-wpcli:
    container_name: ${CONTAINER_NAME}-wpcli
    depends_on:
      - wordpress
      - database
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
      WP_ENV: development
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal

  webpack-dev:
    container_name: ${CONTAINER_NAME}-webpack
    build:
      context: .
      dockerfile: docker/Dockerfile.webpack
    volumes:
      - ./src:/app/src
    depends_on:
      - wordpress
      - database
    command: yarn webpack:dev
    profiles:
      - dev
    networks:
      - internal

  webpack-prod:
    container_name: ${CONTAINER_NAME}-webpack-prod
    build:
      context: .
      dockerfile: docker/Dockerfile.webpack
    volumes:
      - ./src:/app/src
    depends_on:
      - wordpress
    command: yarn webpack:prod
    profiles:
      - prod
    networks:
      - internal

volumes:
  dbdata:
  wordpress:
  wp-content_uploads:

networks:
  internal:
    driver: bridge
